#!/bin/sh

# ---------------------------------------------------------------------- 
# lst: process lists for groff ms or groff man
# ---------------------------------------------------------------------- 
# Copyright (C) 2014 California Institute of Technology
# ---------------------------------------------------------------------- 

html=0

while :; do
  case $1 in
    -v|--version)
      echo 'lst version 1.0'
      exit 0 ;;
    -h|--html)
      html=1 ;;
    --)
      shift
      break ;;
    -?*)
      echo 'usage: lst -v' >&2
      echo '       lst [-h] [--] [files]' >&2
      exit 1 ;;
    *)
      break ;;
  esac
  shift
done

for arg in "$@"; do
  if test $arg != '-' && ! test -e $arg; then
    echo 'lst: file '$arg' does not exist' >&2
    exit 1
  fi
done

if test $html -eq 1
then
  lst-html.awk "$@"
else
  lst.awk "$@"
fi
