#!/bin/sh

# ----------------------------------------------------------------------
# present(1): generate a presentation using groff_mp(7)
# ----------------------------------------------------------------------
# Copyright (c) 2014 California Institute of Technology
# ---------------------------------------------------------------------- 

slide_num=2
unset printout

while :; do
  case $1 in
    -v|--version)
      echo 'present version 1.0'
      exit 0 ;;
    -p)
      printout="-p" ;;
    -s)
      slide_num=$2
      shift ;;
    --)
      shift
      break ;;
    -?*)
      echo 'usage: present -v' >&2
      echo '       present [-p] [-s slide_num] [--] files' >&2
      exit 1 ;;
    *)
      break ;;
  esac
  shift
done

for file in "$@"; do
  echo '.bp'
  slide $printout -n $slide_num "$file"
  slide_num=`expr $slide_num '+' 1`
done
